# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7953e4fdc1bc6d672af20336abf7be6d8c1e6da3197142ac33051fde90d8d4e0cb4891a66d675ec54626bc180592010d4f172b6e14ee49d7a3b19335614e80

test:
  secret_key_base: 20a2ea4354505f4a163a166387a49e84a2687a0bd920bd5fcf52d3e35ea734677fdb928dcb726ff12cdc89b3329cf5522d16979ad58849ce912726050349f757

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
